server:
  port: 8083

spring:
  application:
    name: admin-server
  cloud:
    gateway:
      dicovery:
        locator:
          enabled: true
          lower-case-service-id: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8081/eureka

logging:
  pattern:
    console: "%d{HH:mm:ss} | %-5level | %msg%n"