server:
  port: 8083

logging:
  pattern:
    console: "%d{HH:mm:ss} | %-5level | %msg%n"

spring:
  application:
    name: admin-server

# регистрация у eureka-server
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8081/eureka

