server:
  port: 8082

logging:
  pattern:
    console: "%d{HH:mm:ss} | %-5level | %msg%n"

# регистрация у eureka-server
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8081/eureka


spring:
  application:
    name: api-gateway
  # настройки для api-gateway
  cloud:
    gateway:
      dicovery:
        locator:
          enabled: true
          lower-case-service-id: true
  # регистрация у admin-server
  boot:
    admin:
      client:
        enabled: true
        instance:
          name: api-gateway
          service-host-type: ip
        url: http://localhost:8083

# настройки информации о api-gateway для admin-server
management:
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true
  endpoints:
    web:
      exposure:
        include: '*'