server:
  port: 0

spring:
  application:
    name: eureka-client
  boot:
    admin:
      client:
        enabled: true
        instance:
          name: eureka-client
          service-host-type: ip
        url: http://localhost:8083

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8081/eureka

logging:
  pattern:
    console: "%d{HH:mm:ss} | %-5level | %msg%n"

management:
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true
  endpoints:
    web:
      exposure:
        include: '*'